apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: true
    service.beta.kubernetes.io/aws-load-balancer-type: elb
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0bb0cb878b1c22389,subnet-06f95c087017a7b8e"
  name: rabbitmq-cluster-prod
  namespace: rabbitmq-system
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 500m
    limits:
      cpu: 1
      memory: 1Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer
