apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    name: tcp-5672
    port: 5672
    targetPort: 5672
  - protocol: TCP
    name: tcp-15672
    port: 15672
    targetPort: 15672
  type: LoadBalancer

